#!/bin/bash

# SKELETON
# =============================================================================
# repos may deal with most of this. this is the directory structure the user
# wants to set up automatically.
#
# could just bd xdg standard if that's your thing
# this is the output of `tree -dL 1 ~`

read -r -d '' var_TREE <<-EOF
/home/es
├── bin
├── etc
│   ├── bin
│   ├── cron
│   ├── docs
│   ├── fonts
│   ├── irc
│   ├── mail
│   ├── sec
│   ├── shell
│   ├── utf
│   ├── vcs
│   ├── vim
│   ├── web
│   ├── xmonad
│   └── xorg
├── sec
│   ├── bin
│   └── dictionaries
├── shr
│   └── music
├── tmp
├── var
│   ├── cal
│   ├── Dropbox
│   ├── irc
│   ├── mail
│   └── vim
└── wrk
    ├── archlinux
    ├── code
    ├── sec
    ├── web
    └── write
EOF

# LINKS
# =============================================================================
# Links are source-linktarget pairs. Each link is checked for current state of 
# each pair component. Given the current state, one of several logical actions 
# is performed to bring the link into the desired state.

source_link ~/source/file ~/linkfile

# REPOS
# =============================================================================
# repositories to clone locally. if present no action is taken (never auto 
# updated). Note that these are created before the tree above so they will not
# conflict with existing content. If they do, an error will be logged.

repo http://remote.url/here ~/local/path [repotype]
repo http://remote.url/here ~/local/path [repotype]
repo http://remote.url/here ~/local/path [repotype]
repo http://remote.url/here ~/local/path [repotype]

# SECURE
# =============================================================================
# secure content (non public) and security related settings
# including passwords in text files (terrible but true), ssh key configuration,
# and other such sensitive stuff













# PACKAGES BELOW WILL BE MOVED TO A DIFFERENT PROFILE LATER...

# SYSADMIN
# =============================================================================
package sudo openssh tightvnc
 
# DNS/NETWORK/PENTEST
# =============================================================================
packages dnsutils
#packages macchanger
#packages aircrack-ng aircrack-ng-scripts
#packages compat-wireless-patched
#packages iodine
#modules add tun
#packages sshuttle-git

# DNS/NETWORK/PENTEST
# =============================================================================
packages iptables
daemons add @iptables

# SHELL/CODING/TXT
# =============================================================================
packages zsh terminus-font git mercurial vim
packages gvim curl terminus-font bc gnupg gnupg2 keychain par hunspell
packages rxvt-unicode urxvt-url-select
# par - currently has incorrect architecture values

# HASKELL GENERAL
# =============================================================================

# PRODUCTIVITY & MGMT
# =============================================================================
packages task ledger

# AUR
# =============================================================================
packages curl yajl package-query yaourt burp

# GRAPHICS
# =============================================================================
packages gromit-mpx gimp-devel inkscape

# MISC
# =============================================================================
package fortune-mod-issa-haiku figlet

# HW UTILS
# =============================================================================
packages htop hardinfo powertop-git

# HW UTILS
# =============================================================================
packages mutt offlineimap-git notmuch-git mutt-notmuch muttjump
package msmtp-git # msmtp from AUR as we want the queue scripts
# following w3m compface netpbm used for xface display
# packages w3m compface netpbm

# INTERNET
# =============================================================================
packages newsbeuter # rss
packages googlecl gcalcli
packages weechat-git # irc, seems faster than irssi
packages chromium flashplugin skype
overlay /usr/local/bin/chrome
#packages firefox-aurora pentadactyl-hg
#TODO: to use the multilib flash plugin in firefox, set
#'dom.ipc.plugins.enabled' to true in about:config, otherwise lots of crashes
#install_packages google-earth
#packages hspell uzbl-experimental-git
 
# MEDIA
# =============================================================================
packages mpd mpc mplayer2 youtube-viewer
packages apvlv #PDF; zathura
