#!/bin/bash

# this is an aif config file
# it can work with aif "standard" automic procedure
# or with archproto on top of a system profile

# only stuff specific to me as a user, not the hardware (that goes in the 
# archproto system

HOSTNAME=rho
TIMEZONE=

# TODO: GIT, HOME SETUP STUFF
# note: var could be put back in .local?
# about etc... could it be back in .config? or not?

# how does below interact with procedure?
TARGET_PACKAGES='openssh e2fsprogs cryptsetup lvm2 xfsprogs'

var_PARTITIONS='/dev/sda 100:ext2:+ 2048:swap *:xfs'
var_BLOCKDATA='/dev/sda1 raw no_label ext2;yes;/boot;target;no_opts;no_label;no_params
/dev/sda2 raw no_label swap;yes;no_mountpoint;target;no_opts;no_label;no_params
/dev/sda3 raw no_label dm_crypt;yes;no_mountpoint;target;no_opts;sda3crypt;-c__aes-xts-plain__-y__-s__512
/dev/mapper/sda3crypt dm_crypt no_label lvm-pv;yes;no_mountpoint;target;no_opts;no_label;no_params
/dev/mapper/sda3crypt+ lvm-pv no_label lvm-vg;yes;no_mountpoint;target;no_opts;cryptpool;/dev/mapper/sda3crypt
/dev/mapper/cryptpool lvm-vg cryptpool lvm-lv;yes;no_mountpoint;target;no_opts;cryptroot;5G|lvm-lv;yes;no_mountpoint;target;no_opts;crypthome;5G
/dev/mapper/cryptpool-cryptroot lvm-lv no_label xfs;yes;/;target;no_opts;no_label;no_params
/dev/mapper/cryptpool-crypthome lvm-lv no_label xfs;yes;/home;target;no_opts;no_label;no_params'

